### ISSUE TITLE
Setup error: ./arch-ppa: line 10: mkarchroot: command not found

### ISSUE THREAD

**Issue by ghost** [EnigmaCurry/arch-ppa#12]
I've tried seeing if it's a package that I can install, but nope.

**Comment by EnigmaCurry** [comment]
install `devtools`

https://www.archlinux.org/packages/extra/any/devtools/

FYI this is not something i have used pesonally in quite some time, i have limited ability to support is right now.

**Comment by EnigmaCurry** [comment]
I closed this but you can still follow up here.
